title: 'D Double E'
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'D Double E is a living legend in the Grime scene and considered by many to be the greatest MC of all time.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /news
