title: 'D Double E - Grime MC'
author:
  name: 'D Double E'
  email: blukuwear@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'D Double E is a living legend in the Grime scene and considered by many to be the greatest MC of all time.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /news
